### ISSUE TITLE
Carousel

### ISSUE THREAD

**Issue by 16slowly** [16slowly/Some-Components#2]
图例：

![carousel](https://user-images.githubusercontent.com/15927205/33226794-47018100-d1d0-11e7-9c62-c7b55f27cfca.jpg)

dom:

```jsx
<div class="root">
   <div class="mask mask-left"  />
   <div class="content">{content}</div>
   <
</div>
```
js:

```js
 // 保存 currentIndex
 this.previousIndex = currentIndex

 leave: {
   leaveInLeft:  this.previousIndex < currentIndex  // 向左
   leaveInRight: this.previousIndex > currentIndex   // 向右，previousIndex = 5，currentIndex = 1 时向左
}
```

css: 

```css

.root {
   width: 100%;
   position: relative;
}

.content {
   width: 50%;
   position: absolute;
   top: 0;
   left: 0;
}

.contentEnter {
  
}

.contentLeave {
   
}

.mask {
  width: 50%;
  opacity: 1;
  position: absolute;
  top: 0;
}

// 决定 mask 是放在左边还是右边
.maskRight {
   left: 50%;
}

.maskLeft {
  left: -50%;
}

.maskLeave {
  left: 0%;
  opacity: 0;
}
```
